
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL8Dialect


  application:
    name: HOTEL-SERVICE

server:
  port: 3333

eureka:
  instance:
    prefer-ip-address: true
  client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        default-zone: ${DISCOVERY_URL:http://localhost:8761}/eureka/










